const UPDATE_SETTING_MQTT = 'UPDATE_SETTING_MQTT'
const UPDATE_SETTING_MQTT_REQUEST = 'UPDATE_SETTING_MQTT_REQUEST'
const UPDATE_SETTING_MQTT_ERROR = 'UPDATE_SETTING_MQTT_ERROR'
const UPDATE_SETTING_MQTT_SUCCESS = 'UPDATE_SETTING_MQTT_SUCCESS'
const MQTT_ERROR = 'MQTT_ERROR'

const MQTT_CONNECT_REQUEST = 'MQTT_CONNECT_REQUEST'
const MQTT_CONNECT_SUCCESS = 'MQTT_CONNECT_SUCCESS'
const MQTT_CONNECT_ERROR = 'MQTT_CONNECT_ERROR'

const MQTT_RECONNECT_REQUEST = 'MQTT_RECONNECT_REQUEST'
const MQTT_RECONNECT_SUCCESS = 'MQTT_RECONNECT_SUCCESS'

const MQTT_DISCONNECT = 'MQTT_DISCONNECT'

const MQTT_ADD_SUBSCRIPTIONS = 'MQTT_ADD_SUBSCRIPTIONS'
const MQTT_REMOVE_SUBSCRIPTIONS = 'MQTT_REMOVE_SUBSCRIPTIONS'
const MQTT_REMOVE_SUBSCRIPTIONS_ARRAY = 'MQTT_REMOVE_SUBSCRIPTIONS_ARRAY'
const MQTT_ADD_SUBSCRIPTIONS_ARRAY = 'MQTT_ADD_SUBSCRIPTIONS_ARRAY'

const MQTT_PUBLISH = 'MQTT_PUBLISH'
const MQTT_MESSAGES_TEST = 'MQTT_MESSAGES_TEST'

const INIT_MQTT_REQUESTED = 'INIT_MQTT_REQUESTED'

const MQTT_GATEWAY = 'MQTT_GATEWAY'

export {
  MQTT_GATEWAY,
  MQTT_DISCONNECT,
  UPDATE_SETTING_MQTT,
  MQTT_CONNECT_REQUEST,
  MQTT_CONNECT_SUCCESS,
  MQTT_RECONNECT_REQUEST,
  MQTT_RECONNECT_SUCCESS,
  MQTT_CONNECT_ERROR,
  MQTT_ADD_SUBSCRIPTIONS,
  MQTT_REMOVE_SUBSCRIPTIONS,
  MQTT_PUBLISH,
  MQTT_MESSAGES_TEST,
  MQTT_REMOVE_SUBSCRIPTIONS_ARRAY,
  MQTT_ADD_SUBSCRIPTIONS_ARRAY,
  UPDATE_SETTING_MQTT_ERROR,
  UPDATE_SETTING_MQTT_REQUEST,
  UPDATE_SETTING_MQTT_SUCCESS,
  MQTT_ERROR, 
  INIT_MQTT_REQUESTED,
}
